apiVersion: v1
kind: Service
metadata:
  name: sovereign-cloud-website
  labels:
    app: sovereign-cloud-website
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: sovereign-cloud-website
  type: ClusterIP
